feat: add spring validation to ConfigProperties
International-Data-Spaces-Association/IDS-Messaging-Services pull request #533
Opened 2022-05-20 14:02 UTC by sebplorenz

…if any of these configs is missing. Fixes #532

2022-05-23 11:30 UTC, tmberthold commented
Hello and thank you very much for the contribution! ❤️ 

I ask for a little patience, as I first need to clarify internally how to proceed.

2022-05-31 13:38 UTC, tmberthold requested changes
I apologize for the delay, however, we would need adjustments:
- [ ] Please update the PR once againt development-Branch and resolve conflicts.
- [ ] Most important: Please add the `Fraunhofer IVI` as contributor under the license header after the previous step, if this contribution has been clarified internally by you. 
- [ ] Changelog

2022-06-22 06:29 UTC, tmberthold approved these changes

2022-06-22 07:50 UTC, SebastianOpriel approved these changes

2022-06-22 07:51 UTC, merged